### ISSUE TITLE
Use correct html & sign

### ISSUE THREAD

**Issue by sangjunp4rk** [preissnerkm/prj-rev-bwfs-dasmoto#1]
Use the html & sign instead of just &, which is `&amp;`

https://github.com/preissnerkm/prj-rev-bwfs-dasmoto/blob/master/Dasmotos%20Arts%20%26%20Crafts/index.html#L4

**Comment by preissnerkm** [comment]
ok.  got it.  I misread this the first time, and now see that you have provided me the code.  I've replaced my & in the html code with &amp; in my index.html file.
